"""Automated plain-language report generation."""

from __future__ import annotations

import datetime
import numpy as np
import pandas as pd


def generate_report(
    df:           pd.DataFrame,
    target_col:   str,
    num_cols:     list[str],
    cat_cols:     list[str],
    results_df:   pd.DataFrame,
    feature_importance: dict[str, float],   # orig_name → mean |SHAP|
    warnings:     list[dict],
    log_target:   bool,
    best_model:   str,
) -> str:
    now   = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    n     = len(df)
    n_f   = len(num_cols) + len(cat_cols)
    t     = df[target_col].dropna()

    best_row = results_df[results_df['Model'] == best_model].iloc[0]
    r2       = float(best_row['R²'])
    rmse     = float(best_row['RMSE'])
    mae      = float(best_row['MAE'])

    top_features = sorted(feature_importance.items(), key=lambda x: x[1], reverse=True)[:5]
    top_str      = ', '.join(f"**{n}**" for n, _ in top_features[:3])

    skew = float(t.skew())
    skew_note = (
        f"The target variable has a skewed distribution (skewness = {skew:.2f}), "
        + ("and a **log-transform was applied**, which typically improves model accuracy. "
           if log_target else
           "consider applying a log-transform if model performance seems low. ")
    )

    warn_lines = '\n'.join(
        f"- ⚠️  {w['msg']}" for w in warnings if w['level'] in ('high', 'medium')
    ) or '- ✅  No significant data quality issues detected.'

    model_rows = '\n'.join(
        f"| {row['Model']} | {row['RMSE']:,} | {row['MAE']:,} | {row['R²']:.3f} |"
        for _, row in results_df.iterrows()
    )

    r2_pct = r2 * 100
    r2_interp = (
        'excellent' if r2 > 0.90 else
        'good'      if r2 > 0.75 else
        'moderate'  if r2 > 0.55 else
        'limited'
    )

    report = f"""# House Price Prediction — Analysis Report

**Generated:** {now}
**Dataset:** {n:,} properties · {n_f} features · target: `{target_col}`

---

## Executive Summary

Your dataset contains **{n:,} properties** described by **{n_f} features**
({len(num_cols)} numeric, {len(cat_cols)} categorical).

The best-performing model was **{best_model}** with an **R² of {r2:.3f}**,
meaning it explains approximately **{r2_pct:.0f}% of the variation** in
{target_col} — a {r2_interp} result.

Prediction error (RMSE): **{rmse:,.0f}** · MAE: **{mae:,.0f}**

---

## Target Variable: `{target_col}`

- Mean:   {t.mean():,.0f}
- Median: {t.median():,.0f}
- Std:    {t.std():,.0f}
- Range:  {t.min():,.0f} – {t.max():,.0f}

{skew_note}

---

## Feature Importance (SHAP Analysis)

The strongest predictors of `{target_col}` are {top_str}.

| Rank | Feature | Mean |SHAP| |
|------|---------|-------------|
""" + '\n'.join(
        f'| {i+1} | {name} | {imp:.3f} |'
        for i, (name, imp) in enumerate(top_features)
    ) + f"""

Features with high SHAP values have the largest impact on the model's
predictions — both positively (raising the estimate) and negatively
(lowering it) depending on the property's specific value.

---

## Model Comparison

| Model | RMSE | MAE | R² |
|-------|------|-----|----|
{model_rows}

**Recommendation:** {best_model} achieved the lowest RMSE and is the
recommended model for this dataset.

---

## Data Quality Notes

{warn_lines}

---

## How to Interpret Predictions

The model produces a **point estimate** (most likely price) along with a
**confidence interval** derived from training residuals. The interval
reflects how much the model's predictions typically deviate on similar
data — a wider interval indicates less certainty.

**SHAP waterfall charts** (available in the Explainability tab) show
exactly which features pushed any individual prediction up or down from
the baseline, making the model's reasoning transparent.

---

*Generated by HouseLens — AI-powered housing price analysis tool.*
"""
    return report
